# Generated by Django 4.0.3 on 2022-03-30 14:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import hosts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25, unique=True)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
        ),
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.CharField(max_length=25, unique=True, validators=[hosts.models.reservation_validation])),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('flat', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25, validators=[hosts.models.city_validation])),
                ('income', models.DecimalField(decimal_places=2, max_digits=7)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
